name: Automerge Dependabot patches

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  automerge:
    if: |
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-latest
    permissions: { pull-requests: write, contents: write }
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          merge-method: squash
          target: minor
