version: "3.9"

services:
  strapi:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    env_file:
      - ../server/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - uploads:/app/public/uploads
    ports:
      - "1337:1337"

  nextjs:
    build:
      context: ..
      dockerfile: docker/client.Dockerfile
    env_file:
      - ../client/.env
    depends_on:
      strapi:
        condition: service_started
    ports:
      - "3000:3000"

volumes:
  uploads:
