#!/usr/bin/env sh
# ↓ строка с путём пока оставляем — Husky <10 требует
. "$(dirname -- "$0")/_/husky.sh"

# 1. Линтим только изменённые файлы
npx --no-install lint-staged
# 2. (опционально)  запустим тесты, когда появятся
# yarn test