name: Deploy to VDS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.VDS_HOST }}
      USER: ${{ secrets.VDS_USER }}
      DIR: ${{ secrets.VDS_DIR }}
      PORT: ${{ secrets.VDS_SSH_PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VDS_SSH_KEY }}

      - name: Dump debug vars
        run: |
          echo "SSH_HOST=$SSH_HOST"
          echo "SSH_PORT=$SSH_PORT"

      - name: Add VDS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        run: |
          ssh -p "$PORT" "$USER@$HOST" << 'EOF'
            set -e
            cd "$DIR"
            git pull origin main
            docker compose -f docker/docker-compose.yml pull
            docker compose -f docker/docker-compose.yml up -d --build
          EOF
