name: Deploy to VDS

permissions:
  contents: read
  variables: read

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ vars.VDS_HOST }}
      PORT: ${{ vars.VDS_PORT }}
      USER: ${{ secrets.VDS_USER }}
      DIR: ${{ secrets.VDS_DIR }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VDS_SSH_KEY }}

      - name: Add VDS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ vars.VDS_PORT }}" "${{ vars.VDS_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        run: |
          ssh -p "$PORT" "$USER@$HOST" << 'EOF'
            set -e
            cd "$DIR"
            git pull origin main
            docker compose -f docker/docker-compose.yml pull
            docker compose -f docker/docker-compose.yml up -d --build
          EOF
